### ISSUE TITLE
want a change in the feed section

### ISSUE THREAD

**Issue by sandhucode2001** [OsamaQureshi796/EMS#1]
Hello . I have been Following Your tutorial for making an app like this. Iam new to flutter and I don't know much of it. I want the user to see only the events that is created by that user in the feed section. Can you please tell me where i need to change in the code section and what is the code.

**Comment by OsamaQureshi796** [comment]
Hi @sandhucode2001 ,

Sorry for very late reply but it's logically simple. Just update the query for getting feeds that you only get your feed associated with your UID.

If you still need help let me know i'll check it for you.

Thanks
