### ISSUE TITLE
Opening from the main.dart

### ISSUE THREAD

**Issue by SilvanusTurkson** [OsamaQureshi796/EMS#2]
I'm having issues with it.
This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.
Launching lib\main.dart on Edge in debug mode...
Waiting for connection from debug service on Edge...
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:13:8: Error: Error when reading '/C:/flutter/packages/flutter/lib/src/google_fonts.dart': The system cannot find the file specified.

import '../google_fonts.dart';
       ^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:15:8: Error: Error when reading '/C:/flutter/packages/flutter/lib/src/services/file_io.dart': The system cannot find the file specified.

import 'file_io.dart' // Stubbed implementation by default.
       ^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:18:8: Error: Error when reading '/C:/flutter/packages/flutter/lib/src/services/google_fonts_descriptor.dart': The system cannot find the file specified.

import 'google_fonts_descriptor.dart';
       ^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:19:8: Error: Error when reading '/C:/flutter/packages/flutter/lib/src/services/google_fonts_family_with_variant.dart': The system cannot find the file specified.

import 'google_fonts_family_with_variant.dart';
       ^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:20:8: Error: Error when reading '/C:/flutter/packages/flutter/lib/src/services/google_fonts_variant.dart': The system cannot find the file specified.

import 'google_fonts_variant.dart';
       ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.3.1/lib/src/google_fonts_base.dart:32:1: Error: Type 'AssetManifest' not found.
AssetManifest assetManifest = AssetManifest();
^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:32:1: Error: Type 'AssetManifest' not found.
AssetManifest assetManifest = AssetManifest();
^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:63:16: Error: Type 'GoogleFontsVariant' not found.
  required Map<GoogleFontsVariant, GoogleFontsFile> fonts,
               ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:63:36: Error: Type 'GoogleFontsFile' not found.
  required Map<GoogleFontsVariant, GoogleFontsFile> fonts,
                                   ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:120:34: Error: Type 'GoogleFontsDescriptor' not found.
Future<void> loadFontIfNecessary(GoogleFontsDescriptor descriptor) async {
                                 ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:199:1: Error: Type 'GoogleFontsVariant' not found.
GoogleFontsVariant _closestMatch(
^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:200:5: Error: Type 'GoogleFontsVariant' not found.
    GoogleFontsVariant sourceVariant,
    ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:201:14: Error: Type 'GoogleFontsVariant' not found.
    Iterable<GoogleFontsVariant> variantsToCompare,
             ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:221:5: Error: Type 'GoogleFontsFile' not found.
    GoogleFontsFile file,
    ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:254:19: Error: Type 'GoogleFontsVariant' not found.
int _computeMatch(GoogleFontsVariant a, GoogleFontsVariant b) {
                  ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:254:41: Error: Type 'GoogleFontsVariant' not found.
int _computeMatch(GoogleFontsVariant a, GoogleFontsVariant b) {
                                        ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:268:5: Error: Type 'GoogleFontsFamilyWithVariant' not found.
    GoogleFontsFamilyWithVariant familyWithVariant,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:290:20: Error: Type 'GoogleFontsFile' not found.
bool _isFileSecure(GoogleFontsFile file, Uint8List bytes) {
                   ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:329:3: Error: Type 'AssetMetadata' not found.
  AssetMetadata _chooseVariant(String mainAssetKey, ImageConfiguration config, Iterable<AssetMetadata>? candidateVariants) {
  ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:329:89: Error: Type 'AssetMetadata' not found.
  AssetMetadata _chooseVariant(String mainAssetKey, ImageConfiguration config, Iterable<AssetMetadata>? candidateVariants) {
                                                                                        ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:357:3: Error: Type 'AssetMetadata' not found.
  AssetMetadata _findBestVariant(SplayTreeMap<double, AssetMetadata> candidatesByDpr, double value) {
  ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:357:55: Error: Type 'AssetMetadata' not found.
  AssetMetadata _findBestVariant(SplayTreeMap<double, AssetMetadata> candidatesByDpr, double value) {
                                                      ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.3.1/lib/src/google_fonts_base.dart:32:1: Error: 'AssetManifest' isn't a type.
AssetManifest assetManifest = AssetManifest();
^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.3.1/lib/src/google_fonts_base.dart:32:31: Error: Method not found: 'AssetManifest'.
AssetManifest assetManifest = AssetManifest();
                              ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:32:1: Error: 'AssetManifest' isn't a type.
AssetManifest assetManifest = AssetManifest();
^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:32:31: Error: Method not found: 'AssetManifest'.
AssetManifest assetManifest = AssetManifest();
                              ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:63:16: Error: 'GoogleFontsVariant' isn't a type.
  required Map<GoogleFontsVariant, GoogleFontsFile> fonts,
               ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:63:36: Error: 'GoogleFontsFile' isn't a type.
  required Map<GoogleFontsVariant, GoogleFontsFile> fonts,
                                   ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:87:19: Error: Method not found: 'GoogleFontsVariant'.
  final variant = GoogleFontsVariant(
                  ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:92:29: Error: Method not found: 'GoogleFontsFamilyWithVariant'.
  final familyWithVariant = GoogleFontsFamilyWithVariant(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:97:22: Error: Method not found: 'GoogleFontsDescriptor'.
  final descriptor = GoogleFontsDescriptor(
                     ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:120:34: Error: 'GoogleFontsDescriptor' isn't a type.
Future<void> loadFontIfNecessary(GoogleFontsDescriptor descriptor) async {
                                 ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:149:24: Error: Method not found: 'loadFontFromDeviceFileSystem'.
    byteData = file_io.loadFontFromDeviceFileSystem(familyWithVariantString);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:156:9: Error: Undefined name 'GoogleFonts'.
    if (GoogleFonts.config.allowRuntimeFetching) {
        ^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:200:5: Error: 'GoogleFontsVariant' isn't a type.
    GoogleFontsVariant sourceVariant,
    ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:201:14: Error: 'GoogleFontsVariant' isn't a type.
    Iterable<GoogleFontsVariant> variantsToCompare,
             ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:204:8: Error: 'GoogleFontsVariant' isn't a type.
  late GoogleFontsVariant bestMatch;
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:221:5: Error: 'GoogleFontsFile' isn't a type.
    GoogleFontsFile file,
    ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:242:17: Error: Method not found: 'saveFontToDeviceFileSystem'.
        file_io.saveFontToDeviceFileSystem(fontName, response.bodyBytes));
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:254:19: Error: 'GoogleFontsVariant' isn't a type.
int _computeMatch(GoogleFontsVariant a, GoogleFontsVariant b) {
                  ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:254:41: Error: 'GoogleFontsVariant' isn't a type.
int _computeMatch(GoogleFontsVariant a, GoogleFontsVariant b) {
                                        ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:268:5: Error: 'GoogleFontsFamilyWithVariant' isn't a type.
    GoogleFontsFamilyWithVariant familyWithVariant,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/asset_manifest.dart:290:20: Error: 'GoogleFontsFile' isn't a type.
bool _isFileSecure(GoogleFontsFile file, Uint8List bytes) {
                   ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:285:14: Error: 'AssetManifest' isn't a type.
      .then((AssetManifest manifest) {
             ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:286:24: Error: 'AssetMetadata' isn't a type.
        final Iterable<AssetMetadata>? candidateVariants = manifest.getAssetVariants(keyName);
                       ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:287:15: Error: 'AssetMetadata' isn't a type.
        final AssetMetadata chosenVariant = _chooseVariant(
              ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:284:5: Error: The getter 'AssetManifest' isn't defined for the class 'AssetImage'.
 - 'AssetImage' is from 'package:flutter/src/painting/image_resolution.dart' ('/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'AssetManifest'.
    AssetManifest.loadFromAssetBundle(chosenBundle)
    ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:329:89: Error: 'AssetMetadata' isn't a type.
  AssetMetadata _chooseVariant(String mainAssetKey, ImageConfiguration config, Iterable<AssetMetadata>? candidateVariants) {
                                                                                        ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:334:32: Error: 'AssetMetadata' isn't a type.
    final SplayTreeMap<double, AssetMetadata> candidatesByDevicePixelRatio =
                               ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:335:28: Error: 'AssetMetadata' isn't a type.
      SplayTreeMap<double, AssetMetadata>();
                           ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:336:16: Error: 'AssetMetadata' isn't a type.
    for (final AssetMetadata candidate in candidateVariants) {
               ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:331:14: Error: The method 'AssetMetadata' isn't defined for the class 'AssetImage'.
 - 'AssetImage' is from 'package:flutter/src/painting/image_resolution.dart' ('/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart').
Try correcting the name to the name of an existing method, or defining a method named 'AssetMetadata'.
      return AssetMetadata(key: mainAssetKey, targetDevicePixelRatio: null, main: true);
             ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart:357:55: Error: 'AssetMetadata' isn't a type.
  AssetMetadata _findBestVariant(SplayTreeMap<double, AssetMetadata> candidatesByDpr, double value) {
                                                      ^^^^^^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///C:/flutter/packages/flutter/lib/src/painting/image_resolution.dart, which contains the type: InterfaceType(Iterable<<invalid>>?).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3678)
#1      ProgramCompiler._newEmitType (package:dev_compiler/src/kernel/compiler.dart:3471)
#2      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3379)
#3      ProgramCompiler._emitCast (package:dev_compiler/src/kernel/compiler.dart:7405)
#4      ProgramCompiler.visitAsExpression (package:dev_compiler/src/kernel/compiler.dart:7398)
#5      AsExpression.accept (package:kernel/ast.dart:7635)
#6      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#7      ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compiler.dart:2204)
#8      ProgramCompiler.visitVariableDeclaration (package:dev_compiler/src/kernel/compiler.dart:5314)
#9      VariableDeclaration.accept (package:kernel/ast.dart:10744)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#12     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#13     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#15     new List.of (dart:core-patch/array_patch.dart:39)
#16     SetBase.toList (dart:collection/set.dart:119)
#17     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4701)
#18     Block.accept (package:kernel/ast.dart:9195)
#19     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#20     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#21     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#22     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#23     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#24     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#25     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#26     ProgramCompiler._emitArrowFunction (package:dev_compiler/src/kernel/compiler.dart:7578)
#27     ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7571)
#28     FunctionExpression.accept (package:kernel/ast.dart:8606)
#29     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#30     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6834)
#31     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:5774)
#32     ProgramCompiler.visitDynamicInvocation (package:dev_compiler/src/kernel/compiler.dart:5678)
#33     DynamicInvocation.accept (package:kernel/ast.dart:5571)
#34     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#35     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:5773)
#36     ProgramCompiler.visitDynamicInvocation (package:dev_compiler/src/kernel/compiler.dart:5678)
#37     DynamicInvocation.accept (package:kernel/ast.dart:5571)
#38     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#39     ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:4688)
#40     ExpressionStatement.accept (package:kernel/ast.dart:9142)
#41     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#42     MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#43     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#44     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#45     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#46     new List.of (dart:core-patch/array_patch.dart:39)
#47     SetBase.toList (dart:collection/set.dart:119)
#48     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4701)
#49     Block.accept (package:kernel/ast.dart:9195)
#50     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#51     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#52     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#53     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#54     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#55     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#56     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#57     ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2392)
#58     ProgramCompiler._withMethodDeclarationContext (package:dev_compiler/src/kernel/compiler.dart:4323)
#59     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:2391)
#60     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2332)
#61     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:932)
#62     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:846)
#63     List.forEach (dart:core-patch/growable_array.dart:416)
#64     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:784)
#65     List.forEach (dart:core-patch/growable_array.dart:416)
#66     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#67     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#68     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:794)
<asynchronous suspension>
#69     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:654)
<asynchronous suspension>
#70     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.

**Comment by OsamaQureshi796** [comment]
Hi @SilvanusTurkson ,

Hope this comment finds you well.

Currently EMS only supports android & iOS platforms but it's easy to add the web support.

You just have to follow some instructions from the flutter official website to enable web on exciting flutter project and configure firebase web project.

And the logs that you shared it shows that the plugins need to be upgraded to latest versions like google_fonts and image_picker etc.

I hope this gives you answer to your question.

I'm closing this issue but still if you get some then let me know.

Thanks
